/**
 * The 114 surahs in mushaf order.
 *
 * Every surah has a recitation now that audio comes from the Islamic Network
 * CDN, addressed purely by number. Earlier versions stored a per-surah audio
 * path and had to model "no recitation yet" as a separate case; that
 * distinction is gone, along with the disabled buttons it produced.
 */

export interface Surah {
  readonly number: number;
  readonly name: string;
}

export const SURAHS: readonly Surah[] = [
  { number: 1, name: "সূরা আল ফাতিহা" },
  { number: 2, name: "সূরা আল বাকারা" },
  { number: 3, name: "সূরা আল ইমরান" },
  { number: 4, name: "সূরা আন নিসা" },
  { number: 5, name: "সূরা আল মায়িদা" },
  { number: 6, name: "সূরা আল আন'আম" },
  { number: 7, name: "সূরা আল আরাফ" },
  { number: 8, name: "সূরা আল আনফাল" },
  { number: 9, name: "সূরা আত তওবা" },
  { number: 10, name: "সূরা ইউনুস" },
  { number: 11, name: "সূরা হুদ" },
  { number: 12, name: "সূরা ইউসুফ" },
  { number: 13, name: "সূরা আর রাদ" },
  { number: 14, name: "সূরা ইব্রাহিম" },
  { number: 15, name: "সূরা আল হিজর" },
  { number: 16, name: "সূরা আন নাহল" },
  { number: 17, name: "সূরা বনী ইসরাইল" },
  { number: 18, name: "সূরা আল কাহফ" },
  { number: 19, name: "সূরা মারইয়াম" },
  { number: 20, name: "সূরা তা-হা" },
  { number: 21, name: "সূরা আল আম্বিয়া" },
  { number: 22, name: "সূরা আল হাজ্জ" },
  { number: 23, name: "সূরা আল মুমিনূন" },
  { number: 24, name: "সূরা আন নূর" },
  { number: 25, name: "সূরা আল ফুরকান" },
  { number: 26, name: "সূরা আশ শুআরা" },
  { number: 27, name: "সূরা আন নামল" },
  { number: 28, name: "সূরা আল কাসাস" },
  { number: 29, name: "সূরা আল আনকাবুত" },
  { number: 30, name: "সূরা আর রুম" },
  { number: 31, name: "সূরা লোকমান" },
  { number: 32, name: "সূরা আস সাজদাহ" },
  { number: 33, name: "সূরা আল আহযাব" },
  { number: 34, name: "সূরা সাবা" },
  { number: 35, name: "সূরা ফাতির" },
  { number: 36, name: "সূরা ইয়াসিন" },
  { number: 37, name: "সূরা আস সাফফাত" },
  { number: 38, name: "সূরা সাদ" },
  { number: 39, name: "সূরা আজ জুমার" },
  { number: 40, name: "সূরা আল মুমিন" },
  { number: 41, name: "সূরা হা-মীম আস সাজদাহ" },
  { number: 42, name: "সূরা আশ শূরা" },
  { number: 43, name: "সূরা আয যুখরুফ" },
  { number: 44, name: "সূরা আদ দোখান" },
  { number: 45, name: "সূরা আল জাসিয়া" },
  { number: 46, name: "সূরা আল আহকাফ" },
  { number: 47, name: "সূরা মুহাম্মাদ" },
  { number: 48, name: "সূরা আল ফাতহ" },
  { number: 49, name: "সূরা আল হুজুরাত" },
  { number: 50, name: "সূরা ক্বাফ" },
  { number: 51, name: "সূরা আয যারিয়াত" },
  { number: 52, name: "সূরা আত তুর" },
  { number: 53, name: "সূরা আন নজম" },
  { number: 54, name: "সূরা আল কামার" },
  { number: 55, name: "সূরা আর রহমান" },
  { number: 56, name: "সূরা আল ওয়াকিয়া" },
  { number: 57, name: "সূরা আল হাদিদ" },
  { number: 58, name: "সূরা আল মুজাদিলা" },
  { number: 59, name: "সূরা আল হাশর" },
  { number: 60, name: "সূরা আল মুমতাহিনা" },
  { number: 61, name: "সূরা আস সফ" },
  { number: 62, name: "সূরা আল জুমা" },
  { number: 63, name: "সূরা আল মুনাফিকুন" },
  { number: 64, name: "সূরা আত তাগাবুন" },
  { number: 65, name: "সূরা আত তালাক" },
  { number: 66, name: "সূরা আত তাহরিম" },
  { number: 67, name: "সূরা আল মুলক" },
  { number: 68, name: "সূরা আল কলম" },
  { number: 69, name: "সূরা আল হাক্কা" },
  { number: 70, name: "সূরা আল মাআরিজ" },
  { number: 71, name: "সূরা নুহ" },
  { number: 72, name: "সূরা আল জিন" },
  { number: 73, name: "সূরা আল মুযযাম্মিল" },
  { number: 74, name: "সূরা আল মুদ্দাসসির" },
  { number: 75, name: "সূরা আল ক্বিয়ামাহ" },
  { number: 76, name: "সূরা আল ইনসান" },
  { number: 77, name: "সূরা আল মুরসালাত" },
  { number: 78, name: "সূরা আন নাবা" },
  { number: 79, name: "সূরা আন নাযিয়াত" },
  { number: 80, name: "সূরা আবাসা" },
  { number: 81, name: "সূরা আত তাকভীর" },
  { number: 82, name: "সূরা আল ইনফিতার" },
  { number: 83, name: "সূরা আল মুতাফফিফিন" },
  { number: 84, name: "সূরা আল ইনশিকাক" },
  { number: 85, name: "সূরা আল বুরূজ" },
  { number: 86, name: "সূরা আত তারিক" },
  { number: 87, name: "সূরা আল আ'লা" },
  { number: 88, name: "সূরা আল গাশিয়া" },
  { number: 89, name: "সূরা আল ফাজর" },
  { number: 90, name: "সূরা আল বালাদ" },
  { number: 91, name: "সূরা আশ শামস" },
  { number: 92, name: "সূরা আল লাইল" },
  { number: 93, name: "সূরা আদ দুহা" },
  { number: 94, name: "সূরা আশ শারহ" },
  { number: 95, name: "সূরা আত তীন" },
  { number: 96, name: "সূরা আল আলাক" },
  { number: 97, name: "সূরা আল ক্বদর" },
  { number: 98, name: "সূরা আল বাইয়্যিনাহ" },
  { number: 99, name: "সূরা আয যালযালাহ" },
  { number: 100, name: "সূরা আল আদিয়াত" },
  { number: 101, name: "সূরা আল কারিয়াহ" },
  { number: 102, name: "সূরা আত তাকাসুর" },
  { number: 103, name: "সূরা আল আসর" },
  { number: 104, name: "সূরা আল হুমাযাহ" },
  { number: 105, name: "সূরা আল ফীল" },
  { number: 106, name: "সূরা কুরাইশ" },
  { number: 107, name: "সূরা আল মাউন" },
  { number: 108, name: "সূরা আল কাউসার" },
  { number: 109, name: "সূরা আল কাফিরুন" },
  { number: 110, name: "সূরা আন নাসর" },
  { number: 111, name: "সূরা আল মাসাদ" },
  { number: 112, name: "সূরা আল ইখলাস" },
  { number: 113, name: "সূরা আল ফালাক" },
  { number: 114, name: "সূরা আন নাস" },
];

export function findSurah(number: number): Surah | undefined {
  return SURAHS.find((surah) => surah.number === number);
}

/** Al-Fatiha. What the play button starts when nothing has been chosen. */
export const FIRST_SURAH: Surah = { number: 1, name: "সূরা আল ফাতিহা" };
